name: Build validation

on:
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: |
          if [[ "${{ github.base_ref }}" == "main" ]]; then
            ./mvnw clean install -Dspring.profiles.active=prod -DskipTests
          else
            ./mvnw clean install -Dspring.profiles.active=dev -DskipTests
          fi
